name: nexoft
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  flutter_svg: ^1.1.6
  freezed: ^2.3.3
  json_annotation: ^4.8.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.2.3
  image_picker: ^0.7.2+1
  get: ^4.6.5
  bot_toast: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
  assets:
    - assets/icons/
    - .env
